version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true #개발 단계에서만 사용하는 requirements.dev.txt를 사용할 수 있음
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
